diario-anadia-2022-08-29-proc.txt
post_proc.py

Como após a extração e remoção das linhas em branco o cabeçalho fica na primeira linha, eu uso a primeira palavra dele pra comparar se aparece outras vezes. Não estou usando a linha toda, já que talvez pois alguma coisa pode mudar (ainda não tenho certeza dessa informação), então utilizo a primeira palavra.
A função "delete_header" é responsável pela ação de excluir outras aparições do cabeçalho.

Remover cabeçalho AMA

---

diario-anadia-2022-08-29-proc.txt
post_proc.py

O Professor me guiou e ajudou a pensar numa lógica melhor para a remoção de linhas. @emanuelucas04, depois de revisar e realizar merge você pode plugar a lógica do seu código (de remover preâmbulo) nesse código a seguir. 
Pontos que o professor ressaltou:
- Nesse momento não precisamos separar em funções
- No fim, todas as tarefas eram sobre remover linhas (e a gente não parou pra pensar nisso). Nesse sentido, poderíamos pensar em uma lógica conjunta.
- Pensamos nas tarefas como coisas separadas, mas na realidade elas se juntam em um todo.
- Por que não criar uma lista de linhas a apagar, e simplesmente adicionar os números das linhas nessa lista?
Veja esse código, entenda e realize o merge. A partir disso prossiga com a tarefa de "remover o preâmbulo" tendo como base o main.

Remover Linhas Finais

---

diario-anadia-2022-08-29-gabarito.txt
diario-anadia-2022-08-29-proc.txt
post_proc.py

Boa tarde!
Conseguimos remover o preâmbulo!

Deletar Preâmbulo

---

post_proc_test.py

- Esse setUp é basicamente um BeforeEach.
Eu anotei alguns nomes de município errado, aí atualizei nessa pr tbm pra ficar igual os nomes que tá no pdf do diário.

Adicionando Teste (Nomes de Municípios)

---

docs/README.md

Fix https://github.com/danielfireman/ifal-qd/issues/58
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/63)

Primeira versão do relatório em github pages

---

test_data/diario-completo-2014-05-20-test.json
test_data/diario-completo-2014-06-23-test.json
test_data/diario-completo-2015-03-26-test.json
test_data/diario-completo-2015-04-02-test.json
test_data/diario-completo-2016-01-04-test.json
test_data/diario-completo-2016-02-15-test.json

Os testes não passaram, mas a gente só vai modificar post_proc_test depois, correto? (post_proc_test está desatualizado ao novo formato)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/64)

Modificando Testes 

---

test_data/diario-completo-2017-11-13-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/65)

Modificando Teste 2017-11-13

---

test_data/diario-completo-2017-12-28-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/66)

Modificando Teste 2017-12-28

---

test_data/diario-completo-2022-01-03-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/67)

modificando json 2022/01/03

---

test_data/diario-completo-2018-09-28-test.json
test_data/diario-completo-2022-01-03-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/68)

Refatorando json 2018/09/28

---

test_data/diario-completo-2018-09-28-test.json
test_data/diario-completo-2020-06-29-test.json
test_data/diario-completo-2022-01-03-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/69)

Refatorando json 2020/06/29

---

test_data/diario-completo-2020-05-14-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/70)

modificando json 2020/05/14

---

test_data/test_eleitoral/diario-completo-2020-10-15-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/71)

refatorando json 2020-10-15

---

post_proc_test.py
test_data/diario-completo-2016-10-28-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/73)

2016-10-28

---

post_proc_test.py
test_data/diario-completo-2016-10-14-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/72)

2016-10-14

---

post_proc_test.py
test_data/diario-completo-2018-10-02-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/74)

2018-10-02

---

post_proc_test.py
test_data/diario-completo-2019-07-02-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/75)

2019-07-02

---

post_proc_test.py
test_data/diario-completo-2020-10-30-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/77)

(ano eleitoral) 2020-10-30

---

post_proc_test.py
test_data/diario-completo-2022-08-29-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/78)

2022-08-29

---

test_data/diario-completo-2020-10-01-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/82)

modificando json 2020/10/01

---

test_data/diario-completo-2020-10-01-test.json
test_data/diario-completo-2022-02-14-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/83)

Modificando json 2022 02 14

---

test_data/diario-completo-2021-04-01-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/84)

Modificando json 2021 04 01

---

post_proc.py
post_proc_test.py
test_data/diario-completo-2017-12-28-test.json
test_data/diario-completo-2019-07-02-test.json
test_data/diario-completo-2019-07-05-test.json
test_data/diario-completo-2020-10-01-test.json
test_data/diario-completo-2020-10-15-test.json
test_data/diario-completo-2021-01-15-test.json
test_data/diario-completo-2023-01-02-test.json

No caminho da introdução da funcionalidade, também corrigi alguns testes
Fixes #61
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/94)

Funcionalidade de detectar nomeações

---

post_proc.py
post_proc_test.py
test_data/diario-completo-2017-10-25-test.json
test_data/diario-completo-2019-07-02-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/95)

Funcionalidade de detectar exonerações

---

post_proc.py
test_data/diario-completo-2022-02-14-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/102)

Corrigindo Erro de Captura de CPF

---

docs/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/103)

Corrigindo Erros De Português (docs/README.md)

---

.gitignore
coleta_diarios.sh

Primeira parte de #98
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/105)

Script para coleta de diários

---

.gitignore
post_proc.py
test_data/diario-completo-2022-08-15-test.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/106)

Corrigindo Erro de Quando Existem Nomeações e Exonerações Num Mesmo Ato

---

.github/workflows/main.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/107)

Corrigindo Erro dos Testes

---

coleta_diarios_windows.sh
extrair_diarios.py

Tentei adaptar o arquivo `coleta_diarios_windows.sh` para bat mas não deu certo, então por enquanto irei enviar assim, pois usando um terminal linux no windows como eu utilizei o arquivo funcionou.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/108)

Primeiros passos para a correção do problema dos atos

---

diario_ama.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/111)

Corrigindo Erro de Nome de Variável

---

extrair_atos_windows.sh

Adaptar o funcionamento do script para o windows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/113)

Adicionando "extrair_atos_windows.sh"

---

extrair_atos.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/114)

Consolidando atos em um arquivo

---

docs/site/index.html
docs/site/style.css

Me guiei no seguinte print:
Coloquei uma estilização básica só pra não ficar tudo junto.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/131)

Adicionando Estrutura Base do Site

---

docs/site/index.html
docs/site/index.js

Dados visualizados:
- Média de diários por mês
- Total de diários por mês
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/135)

Adicionando Visualização dos Dados - SITE

---

docs/site/index.html
docs/site/style.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/141)

Adicionando Municípios no Dropdown

---

docs/site/index.html
docs/site/style.css

Mudei a exibição do texto e agora ele está se adaptando aos tamanhos, retirei a barra lateral verde como pedido e retirei a opção de ver no qd.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/151)

Corrigindo Comentários

---

docs/site/index.html

Como ficou:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/152)

Removendo Caixa de Alagoas

---

docs/site/index.html

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/danielfireman/ifal-qd/154)

Adicionando Anos 2018 e 2019 no Site

---

docs/site/dados/geral.json
docs/site_home_data.py

Nessa PR adiciono dados para os meses no arquivo geral e deixo o arquivo geral no mesmo formato dos arquivos dos outros municípios.
Precisamos verificar em breve a corretude dos dados.

Adicionando Dados dos Meses no Arquivo Geral

---

docs/site/dados/geral.json
docs/site_home_data.py

Essa PR se utiliza de análise de dados com a lib pandas para adicionar os seguintes campos no geral.json:
```
"ranking_nomeacoes": {
"1": {
"nome": nome...,
"num_nomeacoes": numero...
},
..
},
"ranking_exoneracoes": {
"1": {
"nome": nome...,
"num_exoneracoes": numero...
},
...
}
```

Ranking Dos Municípios (Nomeação e Exoneração)
